version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - chess-net

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - chess-net

networks:
  chess-net:
    driver: bridge